### ISSUE TITLE
System.InvalidOperationException: Unable to find view

### ISSUE THREAD

**Issue by bentoaldohax** [soundaranbu/RazorTemplating#47]
I created a Razor class library where I put my view, but the RenderAsync method can't find the view and throws this exception. I don't know what I am doing wrong.

----
System.InvalidOperationException: Unable to find view '~/Notifications.EmailTemplates/Invoice.cshtml'. The following locations were searched:
~/Notifications.EmailTemplates/Invoice.cshtml
Hint:
- Check whether you have added reference to the Razor Class Library that contains the view files.
- Check whether the view file name is correct or exists at the given path.
- Refer documentation or file issue here: https://github.com/soundaranbu/RazorTemplating
   at Razor.Templating.Core.RazorViewToStringRenderer.FindView(ActionContext actionContext, String viewName)
   at Razor.Templating.Core.RazorViewToStringRenderer.RenderViewToStringAsync[TModel](String viewName, TModel model, ViewDataDictionary viewDataDictionary)
   at Razor.Templating.Core.RazorViewToStringRenderer.RenderViewToStringAsync[TModel](String viewName, TModel model)
   at Razor.Templating.Core.RazorTemplateEngine.RenderAsync[TModel](String viewName, TModel model)
   at Notifications.Api.Endpoints.PostSendEmailEndpoint.HandleAsync(PostSendEmailRequest request, CancellationToken ct) in C:\Users\PY-DEV01\Documents\GitHub\Notifications\Notifications.Api\Endpoints\PostSendEmailEndpoint.cs:line 75

-----
![image](https://user-images.githubusercontent.com/104450705/187516854-34e56723-80a8-4b4a-9b4c-4b4efdbaef09.png)

**Comment by soundaranbu** [comment]
Hi @bentoaldohax, please remove the project name from the view path & then try again.

**Comment by bentoaldohax** [comment]
It works. Thanks.
